language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run generate:gh-pages

script:
  - echo "Skipping tests"

deploy:
  provider: pages:git
  edge: true
  skip-cleanup: true
  token: ${GITHUB_TOKEN}
  target-branch: gh-pages
  local_dir: dist
  on:
    branch: master
